---
# Unlisted environments will not be visible on the AppSignal site,
# Active environments count towards the account plan limit.
development:
  # Go to https://appsignal.com if you want to monitor your development
  # environment to obtain an api key.
  # api_key: <DEVELOPMENT-API-KEY>
  active: false
production:
  api_key: 'b698329a-99fa-4f80-bf3e-61343012785c'
