development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: game_on_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: game_on_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: game_on_development
  pool: 5
